let num1;
num1 = prompt("Ingresa un numero: ");
var num2;
num2 = prompt("Ingresa otro numero");
let suma=parseInt (num1) + parseInt (num2);
let resta= num1 - num2;
let division= num1 / num2;
let multiplicacion= num1 * num2;
console.log('La suma es: '+suma);
console.log('La resta es: ' +resta);
console.log('La division es: ' +division);
console.log('La multiplicacion es: ' +multiplicacion);